### PR TITLE
fixes dataconstructors

### PR DESCRIPTION
**Pull request by kritzcreek**
1. Curries the dataconstructors
2. removes the prepended ! before valueN keys

With this I was able to write some basic combinators on ADTs

### CODE REVIEW

**Comment by andyarvanitis** [comment]
Looks good, thanks! This was leftover from when I was trying out having _all_ the functions uncurried, and using clojure's `partial` on the application side (which I would prefer, for various reasons). I switched back everything else and didn't get back to the data constructors. Currying the data constructors is at least consistent with all the other functions this way.

But I might like to change it back to uncurried at some point. In other words, having something like this on the application side (code not compiled):

``` Haskell
  valueToLisp e@App{} = do
    let (f, args) = unApp e []
    args' <- mapM valueToLisp args
    case f of
      Var (_, _, _, Just IsNewtype) _ -> return (head args')
      Var (_, _, _, Just (IsConstructor _ fields)) name
        | length args == length fields -> do
            f' <- valueToLisp f
            return $ LispApp f' args'
        | otherwise -> do
            f' <- valueToLisp f
            return $ LispApp (LispVar "partial") (f' : args')
...etc
```

My attempts at having everything uncurried didn't work due to missing type info for some values coming from `CoreFn` (which I've been meaning to ask Phil and Gary about). I'm doing similar work on the C++ backend right now, as optimizations, in fact.

**Comment by kritzcreek** [comment]
At one point in time I used a macro that curried a function when defining it. That was actually kind of nice but would require a little bit of a runtime.

```
(defn-curried add [x y] 
  (+ x y))
```

This created a function that could be called with 0,1 or 2 arguments and give you a either a function taking the remaining arguments or returning the evaluated result.

This macro is practical for our compilation because we are not using the multi-arity style clojure usually applies.

**Comment by andyarvanitis** [comment]
Interesting! I wonder how much performance is affected by currying (in general) in Clojure? I'm definitely seeing overhead in C++. Not that the clojure backend is at the optimization stage anyway.

**Comment by andyarvanitis** [comment]
I'll go ahead and merge this now and we can easily revisit later.

**Comment by kritzcreek** [comment]
Sure. It's not a big change anyway. 

I'm currently seeing breakage for lambdas  `\x y -> x + y` compiles to:
`(fn [x] (fn [y] ((+ x y))))`
which tries to evaluate a number as a function and breaks. Is the Lisp AST maybe missing atoms?

**Comment by andyarvanitis** [comment]
I hadn't explored atoms, but that just looks like an unintentional extra set of parentheses around the `(+ x y)` expression. I put a space before the closing brace to flag a function call with no args.

**Pull request merged**
